### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by whereismyjetpack** [corylown/edtf-humanize#38]
Hi folks! Is this gem still maintained? If not, would you all mind if Penn State forked it to add ruby3 support?

**Comment by corylown** [comment]
Thanks for the nudge @whereismyjetpack. I've take over the repository from duke-libraries and just published a new release with ruby3 support: https://rubygems.org/gems/edtf-humanize/versions/2.1.0

**Comment by whereismyjetpack** [comment]
Thank you kindly, sir!
